groups:
- name: hello-world-alerts
  rules:
  - alert: HighRequestLatency
    expr: histogram_quantile(0.99, sum(rate(http_request_duration_seconds_bucket{app="hello-world"}[5m])) by (le)) > 1
    for: 5m
    labels:
      severity: critical
    annotations:
      summary: "High request latency detected"
      description: "The 99th percentile request latency is above 1 second."

  - alert: HighErrorRate
    expr: rate(http_requests_total{app="hello-world", status=~"5.."}[5m]) > 0.1
    for: 5m
    labels:
      severity: critical
    annotations:
      summary: "High error rate detected"
      description: "The error rate is above 10%."

  - alert: HighCPUUsage
    expr: sum(rate(container_cpu_usage_seconds_total{container="hello-world"}[5m])) by (pod) > 0.8
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "High CPU usage detected"
      description: "The CPU usage is above 80%."

  - alert: HighMemoryUsage
    expr: sum(container_memory_usage_bytes{container="hello-world"}) by (pod) / sum(container_spec_memory_limit_bytes{container="hello-world"}) by (pod) > 0.8
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "High memory usage detected"
      description: "The memory usage is above 80%."