replicaCount: 1

image:
  repository: hello-world-fastapi
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: NodePort
  port: 8000

ingress:
  enabled: true
  className: "traefik"
  hosts:
    - host: hello-world.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

serviceAccount:
  create: true
  name: ""

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80